### ISSUE TITLE
making a sapi5 implimentation to use with windows programs

### ISSUE THREAD

**Issue by king-dahmanus** [shivammehta007/Neural-HMM#10]
hello. I'm not a dev, but i suggest addin a windows version which is compatible with sapi5(speech application programming interface) for use with different types of programs like textreaders, screenreaders for blind people etc. The voice has to be optimized for responsiveness if you can do that. If that can't be achieved with this neural network thing, then would making an hts tts high quality clone out of it do the job correctly? I dunno, we could discuss this. Thanks and sorry, I'm kind of in a hurry, that's why the post's breaf. Thanks again

**Comment by ghenter** [comment]
Thank you for your interest and for sharing your thoughts.

> i suggest addin a windows version which is compatible with sapi5(speech application programming interface) for use with different types of programs like textreaders, screenreaders for blind people etc. The voice has to be optimized for responsiveness if you can do that.

"Responsiveness" can mean many things, such as being faster than real time and/or being incremental. It is not clear from your post which aspects you are referring to. In terms of incrementality, the neural HMM TTS architecture in this repository requires the complete utterance to be available before it can start speaking, due to features inherited from Tacotron 2. In other words, this is not incremental TTS. This can be changed by tweaking the encoder architecture, and we might do so in future extensions of our research, but it's not likely in the near future.

As for SAPI 5, I don't think integration with any such APIs is in the cards from us. The current version of neural HMM TTS was not created with assistive technology in mind, and is likely not a good fit for such applications. In general, we are researchers, funded to produce and publish novel scientific results in the area of pure and applied machine learning. Our livelihood lies in cutting-edge research, not in development, engineering, productification, deployment, etc. Frustrating as it may be for SAPI 5 users, I don't think I can argue that an SAPI 5 implementation of our method is going to produce the most interesting scientific return for our project.

> would making an hts tts high quality clone out of it do the job correctly?

Are you suggesting first training neural HMM TTS on a speech database, then using the trained neural HMM system to synthesise a lot of speech, and finally training HTS on that synthetic speech? I don't think that will give any better results than just training HTS on the original speech database to begin with. The longer route will just produce a slightly-worse-sounding HTS system, I think.

**Comment by king-dahmanus** [comment]
well, as for the responsiveness, I mean it to be faster than realttime and lagless and with no delay. 
Can't you create a branch of the project and sapify it for asistive tech users?
And for the hts thing, just creating a standard high quality hts voice like rhvoice does it, but of course with high inteligibility, humanlike prosody and things like that. Rhvoice's voices are a bit limited when it comes to inflection, and they don't handle punctuation correctly, but they're very responsive and great. Hope this helps

**Comment by king-dahmanus** [comment]
in other words, just training hts on the original speech database should work well

**Comment by ghenter** [comment]
> Can't you create a branch of the project and sapify it for asistive tech users?

As previously suggested, I cannot justify devoting our limited resources into such work without a compelling research motivation. Even a dedicated branch of this project is unlikely to provide the affordances that matter the most in assistive applications.

If other people want to take a stab at this, they are more than welcome to do so.

> just creating a standard high quality hts voice like rhvoice does it, but of course with high inteligibility, humanlike prosody and things like that. Rhvoice's voices are a bit limited when it comes to inflection, and they don't handle punctuation correctly, but they're very responsive and great.

HTS and neural HMMs are very different on the inside. I think I understand the strengths and weaknesses of RHVoice that you are referring to, but creating a system with all the properties you describe is, in my personal opinion, a multi-year project in itself, and falls outside the scope of this humble repository.

**Comment by king-dahmanus** [comment]
I understand. So ou're saying that this project will never be sapified at all because it is just research?
Actually it could be done n a shorter time if you use rhvoice to create it based on the dictionary that it has, then ajusting the quality of the voice to be as inteligible as it can get, possibly like google tts on android. It's hts but it's cleaner than rhvoices

**Comment by king-dahmanus** [comment]
I understand. So ou're saying that this project will never be sapified at all because it is just research?
Actually it could be done n a shorter time if you use rhvoice to create it based on the dictionary that it has, then ajusting the quality of the voice to be as inteligible as it can get, possibly like google tts on android. It's hts but it's cleaner than rhvoices

**Comment by ghenter** [comment]
> just training hts on the original speech database should work well

I have never trained an HTS system myself, and I have no interest in doing so at the moment. That said, the data we used to train the systems in our paper and on our demo webpage is [the LJ Speech Dataset](https://keithito.com/LJ-Speech-Dataset/), which is freely available online for anyone to try training systems on.

> I understand. So ou're saying that this project will never be sapified at all because it is just research?

Yes. We cannot know what the future holds, but SAPIyfing this system is not on our radar for the foreseeable future.

**Comment by king-dahmanus** [comment]
ok then. I respect your desision. So do you have anything we can discuss or should I close this issue?

**Comment by ghenter** [comment]
I think it can be closed. If our future research brings systems that are a better match for SAPI 5 we might revisit this decision.

**Comment by king-dahmanus** [comment]
yeah maybe sharing this code so others can sapify it is a good idea

**Comment by king-dahmanus** [comment]
that was my mistake sorry

**Comment by king-dahmanus** [comment]
ok then I'll close it now. Hope this project succeeds for you
